use optimistic padding approach

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,15 +34,20 @@ jobs:
           then
             echo "MDS updated:"
             cut -d. -f2 mds.blob | tr '_-' '/+' | tr -d '\n' > mdsBody.b64
-            let b64Size=$(wc -c mdsBody.b64 | awk '{ print $1 }')
-            echo base64 size: _${b64Size}_
-            let modulo=$(expr ${b64Size} % 4)
-            echo modulo: ${modulo}
-            if [ "${modulo}" == "2" ]
-            then
-              echo -n "==" >> mdsBody.b64
-            fi
+            # optimistic: assume no padding needed
             base64 -d mdsBody.b64 | jq . > mdsBody.json
+            if [ $? -ne 0 ]
+            then
+              # was too optimistic: add padding
+              echo "Adding padding"
+              echo -n "==" >> mdsBody.b64
+              base64 -d mdsBody.b64 | jq . > mdsBody.json
+              if [ $? -ne 0 ]
+              then
+                echo "Failed to parse JSON"
+                exit 1
+              fi
+            fi
             echo -n "let mdsJson=" > js/mds.js
             cat mdsBody.json >> js/mds-new.js
             sed "s+let mdsJson={+{+" js/mds.js | jq -r ".entries[].metadataStatement.description" > prev.authrs
